MeiditationActivity/Controllers/ApplicationUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MeiditationActivity.Data;
using MeiditationActivity.Models;
using MeiditationActivity.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MeiditationActivity.Controllers
{
	public class ApplicationUserController : Controller
	{
		private readonly ApplicationDbContext _context;
		private readonly IApplicationUser _userService;
		private readonly UserManager<ApplicationUser> _userManaer;
		public ApplicationUserController(IApplicationUser userService, UserManager<ApplicationUser> userManaer, ApplicationDbContext context)
		{
			_context = context;
			_userManaer = userManaer;
			_userService = userService;

		}
		public IActionResult Index()
		{
			var model = _userService.GetAll();


			return View(model);
		}

		public IActionResult Detail(string id)
		{
			var model = _context.RangeMeters.Find(id)
				;
			//var user = _userManaer.GetUserId();
		//	var user = _userManaer.FindByNameAsync(User.Identity.Name);
		;


			var veiwModel = new UserDetailViewModel
			{
			 
				Id= model.Id,
				PhysicalLoad=model.PhysicalLoad,
				SleepQuality=model.SleepQuality,
				User=model.User,
				UserId=model.UserId,
				
				
				

			};

			return View(veiwModel);


		}
	}
}

MeiditationActivity/Controllers/MeditationAppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MeiditationActivity.Data;
using MeiditationActivity.Models;
using MeiditationActivity.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MeiditationActivity.Controllers
{
    public class MeditationAppController : Controller
    {
		public static UserManager<ApplicationUser> _userMnager;
		private readonly ApplicationDbContext _context;
		public MeditationAppController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
		{
			_context = context;
			_userMnager = userManager;
		}

		[Authorize]
		public async Task<IActionResult> Create()
		{
			// post = _context.Ranges.Include(r => r.User);

			/*var range = _context.Ranges.Select(rangeMeter=> new CreateRangeViewModel
			{
				Id= rangeMeter.Id,
				UserId=user.Id,
				Name=User.Identity.Name,
				PhysicalLoad=rangeMeter.PhysicalLoad,
				PhysicalStatusRate=rangeMeter.PhysicalStatusRate,
				MentalStausRate=rangeMeter.MentalStausRate,
				sleepingHour=rangeMeter.sleepingHour,
				SleepQuality=rangeMeter.SleepQuality,
				weight=rangeMeter.weight,
			}
				); */




			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Create(CreateRangeViewModel model)
		{

			//var userId = _userMnager.GetUserId(User);
			//var user = _userMnager.FindByIdAsync(userId);
			//var claimIdenttiy = (ClaimsIdentity)this.User.Identity;
			//var claim = claimIdenttiy.FindFirst(ClaimTypes.NameIdentifier);
			//model.UserId = claim.Value;

			//var claimUser = _context.Ranges.Where(r => r.UserId == model.UserId).FirstOrDefault();
			var user = await _userMnager.FindByNameAsync(User.Identity.Name);
			var currentDate = DateTime.Now;

			RangeMeter newRange = new RangeMeter
			{
				Created = currentDate,
				MentalStausRate = model.MentalStausRate,
				PhysicalLoad = model.PhysicalLoad,
				PhysicalStatusRate = model.PhysicalStatusRate,
				sleepingHour = model.sleepingHour,
				SleepQuality = model.SleepQuality,
				User = user,
				UserId = user.Id


			};
			_context.RangeMeters.Add(newRange);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}

	//	[Authorize(Roles ="Admin")]
		public IActionResult Index()
		{
			var model = _context.RangeMeters.Include(c=>c.User);


			return View(model);
		}


		[HttpGet]
		public IActionResult GetAll()

		{
			return Json(new { data = _context.RangeMeters.Include(c=>c.User) }) ;
			//return Json(new { data = _unitOfWork.Service.GetAll(includeProperties: "Category,Frequency") });
		}



	}
}

MeiditationActivity/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<MeiditationActivity.Models.ApplicationUser> UserManager
@inject SignInManager<MeiditationActivity.Models.ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>



    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MeiditationActivity</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />

    <style>
        .bg-blue {
            background-color: #282D64;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar bg-blue navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3" style="">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">MeiditationActivity</a>

               
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>


                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="MeditationApp" asp-action="Create">MeditationApp</a>
                                </li>

                                if (User.IsInRole("Admin"))
                                {
                                   
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="MeditationApp" asp-action="Index">Activity</a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-area="" asp-controller="ApplicationUser" asp-action="Index">User</a>
                                    </li>
                                }



                            }

                        </ul>
                    </div>
                </div>
        </nav>
    </header>
                
    <main role="main" class="pb-3">
        @RenderBody()
    </main>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MeiditationActivity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>